name: Node.js Package

on:
  push:
    tags:
      - '*'

permissions:
  packages: write
  contents: write
  pull-requests: write
env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@ZenTwipped'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
